server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/medicare-config-repo
          clone-on-start: true
          default-label: main
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always