server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/IT214_Microservices/Session04/b4/medicare-config-repo
          default-label: main
          clone-on-start: true
          search-paths: '{application}'